[package]
name = "crockford"
version = "1.0.0"
authors = ["J/A <archer884@gmail.com>"]
license = "MIT/Apache-2.0"
description = """
Provides Crockford 32-bit encoding for identifiers (e.g. u64 values).

There was already another library that did Crockford encoding, but it operated on a slice of 
bytes or something like that, and it was really annoying to use. This one is pretty much a 
translation of an existing C# library that does only "the needful."
"""

[dependencies]
